# Generated by Django 4.2.4 on 2024-02-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_subjectmodel_weighted_grade_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='credit_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='marks_obtained',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='weighted_grade_point',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='subjectmodel',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.student'),
        ),
    ]
